export const milestones = [
  {
    id: "AD-GATE-00",
    label: "Foundation",
    title: "Reproducible toolchain and repository",
    stage: 0,
    accent: "blue",
    summary: "Prove that a clean machine can clone, configure, build, and test the permanent project structure.",
    requirements: ["Pinned dependency workflow", "Client, server, shared, tools, and tests targets", "CI and sanitizer lanes", "Git and LFS rules"],
  },
  {
    id: "AD-GATE-01",
    label: "Feel contract",
    title: "Third-person combat feel probes",
    stage: 2,
    accent: "violet",
    summary: "Make movement, targeting, attack timing, block, and dodge rules explicit before durable combat code expands.",
    requirements: ["Camera-relative movement", "Independent camera and facing", "Soft target and Tab lock", "Three-hit chain, block, and dodge probes"],
  },
  {
    id: "AD-GATE-02",
    label: "Vertical slice",
    title: "Local authoritative vertical slice",
    stage: 4,
    accent: "orange",
    summary: "Complete a real 10–15 minute solo run through the same authoritative server path used online.",
    requirements: ["One complete class and weapon package", "Three enemies and one boss", "Personal loot, inventory, progression, and save", "Debug tools and automated rules tests"],
  },
  {
    id: "AD-GATE-03",
    label: "Online proof",
    title: "Two-player authoritative proof",
    stage: 5,
    accent: "blue",
    summary: "Finish the slice with two remote clients under representative latency and loss without corrupting progression.",
    requirements: ["Prediction and reconciliation", "Snapshot interpolation", "Party, revive, and reconnect", "Server-owned combat and loot"],
  },
  {
    id: "AD-GATE-04",
    label: "Scale proof",
    title: "Eight-player stress slice",
    stage: 6,
    accent: "violet",
    summary: "Demonstrate readable, measurable combat at the intended party cap through progressive 2/4/6/8 tests.",
    requirements: ["Bounded server and bandwidth budgets", "Readable ally and enemy signals", "Two-hour soak and induced loss", "Reward and save integrity"],
  },
  {
    id: "AD-GATE-05",
    label: "Ship gate",
    title: "Steam Early Access readiness",
    stage: 7,
    accent: "green",
    summary: "Prepare a replayable game, honest store presence, repeatable packages, support, and patch operations.",
    requirements: ["Steam branches and depot rehearsal", "Crash, logs, and support workflow", "Accessibility and controller checks", "Honest current-state Early Access copy"],
  },
] as const;

